matrix:
  include:
    - language: python
      python: "3.8.2"
      before_install:
        - pwd
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip install -U --force-reinstall pyqt5
        - pip install pyserial
        - pip install codecov
      script:
        - pytest
      after_success:
        - codecov
    
    - language: c
      cache:
        directories:
          - ~/arduino_ide
          - ~/.arduino15/packages/
      env:
        global:
          # You can uncomment this to explicitly choose an (old) version of the Arduino IDE
          - ARDUINO_IDE_VERSION=1.8.11
          - PRETTYNAME="HexaphobUS (Arduino)"
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
      install:
        # Note that every library should be installed in a separate command
        - arduino --install-library "Adafruit SleepyDog Library"
        - arduino --install-library "Adafruit FONA Library"
        - arduino --install-library "Adafruit PWM Servo Driver Library"
        - arduino --install-library "AUnit"
      script:
        - build_main_platforms
      after_success:
        - source < (curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)

os: linux
  sudo: required
  env: BUILDARCH=x64
  dist: bionic

branches:
  only:
    - code

addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - doxygen

git:
  depth: false
  quiet: true

script:
  - doxygen ../docs/Doxyfile

deploy:
  provider: pages
  local_dir: ../docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: code

notifications:
  email:
    on_success: change
    on_failure: change

# {
#   language: ruby,
#   os: [
#     - linux
#   ],
#   branches: {
#     only: [
#       - code
#     ]
#   },
#   addons: {
#     apt: {
#       packages: [
#         - x11-utils
#         - libxkbcommon-x11-0
#         - doxygen
#       ]
#     }
#   },
#   git: {
#     depth: false,
#     quiet: true
#   },
#   script: [
#     - doxygen ../docs/Doxyfile
#   ],
#   deploy: [
#     {
#       provider: pages,
#       local_dir: ../docs/html,
#       on: {
#         branch: [
#           code
#         ]
#       },
#       token: $GH_REPO_TOKEN
#     }
#   ],
#   notifications: {
#     email: [
#       {
#         on_success: change,
#         on_failure: change
#       }
#     ]
#   },
#   jobs: {
#     include: [
#       {
#         language: python,
#         python: "3.8.1",
#         before_install: [
#           - pwd,
#           - python --version,
#           - pip install -U pip,
#           - pip install -U pytest,
#           - pip install -U --force-reinstall pyqt5,
#           - pip install pyserial
#           - pip install codecov
#         ],
#         script: [
#           - pytest
#         ],
#         after_success: [
#           - codecov
#         ]
#       },
#       {
#         language: c,
#         sudo: false,
#         cache: {
#           directories: [
#             - ~/arduino_ide,
#             - ~/.arduino15/packages/
#           ]
#         },
#         env: [
#           {
#             global: [
#               - ARDUINO_IDE_VERSION=1.8.11
#               - PRETTYNAME="HexaphobUS (Arduino)"
#             ]
#           }
#         ],
#         before_install: [
#           - source < (curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
#         ],
#         install: [
#           - arduino --install-library "Adafruit SleepyDog Library",
#           - arduino --install-library "Adafruit FONA Library",
#           - arduino --install-library "Adafruit PWM Servo Driver Library",
#           - arduino --install-library "AUnit"
#         ],
#         script: [
#           - build_main_platforms
#         ],
#         after_success: [
#           - source < (curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
#         ]
#       }
#     ]
#   }
# }